version: '3'
services:
  mysql-db-1:
    image: "mysql:8.0"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=chariot
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - mysql-db-1-data:/var/lib/mysql
      # - ./mysql/h1.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf:ro
    ports:
      - 3411:3306
    networks:
      mysql-net:
        ipv4_address: 172.40.0.11
  mysql-db-test:
    image: "mysql:8.0"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=chariot_test
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3407:3306
    networks:
      mysql-net:
        ipv4_address: 172.40.0.99
  phpmyadmin:
    image: "phpmyadmin:5.2"
    restart: always
    ports:
      - 8041:80
    environment:
      - PMA_HOSTS=mysql-db-1,mysql-db-test
    depends_on:
      - mysql-db-1
      - mysql-db-test
    networks:
      mysql-net:
        ipv4_address: 172.40.0.101
  proxy:
    image: "haproxy:2.6"
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 8040:80 # stats
      - 3400:3300 # mysql primary
      - 3401:3301 # mysql secondary
    networks:
      mysql-net:
        ipv4_address: 172.40.0.102
volumes:
  mysql-db-1-data:
networks:
  mysql-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16
