// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/session.go

// Package mock_session is a generated GoMock package.
package mock_session

import (
	context "context"
	reflect "reflect"

	session "github.com/go-seidon/chariot/internal/session"
	system "github.com/go-seidon/provider/system"
	gomock "github.com/golang/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSession) CreateSession(ctx context.Context, p session.CreateSessionParam) (*session.CreateSessionResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, p)
	ret0, _ := ret[0].(*session.CreateSessionResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionMockRecorder) CreateSession(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSession)(nil).CreateSession), ctx, p)
}

// VerifySession mocks base method.
func (m *MockSession) VerifySession(ctx context.Context, p session.VerifySessionParam) (*session.VerifySessionResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySession", ctx, p)
	ret0, _ := ret[0].(*session.VerifySessionResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// VerifySession indicates an expected call of VerifySession.
func (mr *MockSessionMockRecorder) VerifySession(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySession", reflect.TypeOf((*MockSession)(nil).VerifySession), ctx, p)
}
