openapi: "3.0.0"
info:
  title: Chariot Specification
  version: 0.0.1-$REVISION
  description: Chariot server for goseidon
  contact:
    name: Support
    url: https://github.com/go-seidon/
    email: raka.suryaardi@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000/
    description: local
paths:
  /:
    $ref: "./path/info.yml"
components:
  parameters:
    objectId: 
      $ref: "./parameter/object_id.yml"
    correlationId: 
      $ref: "./parameter/correlation_id.yml"
  schemas:
    ResponseBodyInfo:
      $ref: "./schema/response_body_info.yml"

    GetAppInfoResponse:
      $ref: "./operation/get-app-info/schema_response.yml"
    GetAppInfoData:
      $ref: "./operation/get-app-info/schema_data.yml"

  securitySchemes:
    basicAuth:
      $ref: "./security/basic.yml"
