// Code generated by MockGen. DO NOT EDIT.
// Source: internal/file/file.go

// Package mock_file is a generated GoMock package.
package mock_file

import (
	context "context"
	reflect "reflect"

	file "github.com/go-seidon/chariot/internal/file"
	system "github.com/go-seidon/provider/system"
	gomock "github.com/golang/mock/gomock"
)

// MockFile is a mock of File interface.
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *MockFileMockRecorder
}

// MockFileMockRecorder is the mock recorder for MockFile.
type MockFileMockRecorder struct {
	mock *MockFile
}

// NewMockFile creates a new mock instance.
func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &MockFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFile) EXPECT() *MockFileMockRecorder {
	return m.recorder
}

// DeleteFileById mocks base method.
func (m *MockFile) DeleteFileById(ctx context.Context, p file.DeleteFileByIdParam) (*file.DeleteFileByIdResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileById", ctx, p)
	ret0, _ := ret[0].(*file.DeleteFileByIdResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// DeleteFileById indicates an expected call of DeleteFileById.
func (mr *MockFileMockRecorder) DeleteFileById(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileById", reflect.TypeOf((*MockFile)(nil).DeleteFileById), ctx, p)
}

// GetFileById mocks base method.
func (m *MockFile) GetFileById(ctx context.Context, p file.GetFileByIdParam) (*file.GetFileByIdResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileById", ctx, p)
	ret0, _ := ret[0].(*file.GetFileByIdResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// GetFileById indicates an expected call of GetFileById.
func (mr *MockFileMockRecorder) GetFileById(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileById", reflect.TypeOf((*MockFile)(nil).GetFileById), ctx, p)
}

// ProceedDeletion mocks base method.
func (m *MockFile) ProceedDeletion(ctx context.Context, p file.ProceedDeletionParam) (*file.ProceedDeletionResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProceedDeletion", ctx, p)
	ret0, _ := ret[0].(*file.ProceedDeletionResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// ProceedDeletion indicates an expected call of ProceedDeletion.
func (mr *MockFileMockRecorder) ProceedDeletion(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProceedDeletion", reflect.TypeOf((*MockFile)(nil).ProceedDeletion), ctx, p)
}

// ProceedReplication mocks base method.
func (m *MockFile) ProceedReplication(ctx context.Context, p file.ProceedReplicationParam) (*file.ProceedReplicationResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProceedReplication", ctx, p)
	ret0, _ := ret[0].(*file.ProceedReplicationResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// ProceedReplication indicates an expected call of ProceedReplication.
func (mr *MockFileMockRecorder) ProceedReplication(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProceedReplication", reflect.TypeOf((*MockFile)(nil).ProceedReplication), ctx, p)
}

// RetrieveFileBySlug mocks base method.
func (m *MockFile) RetrieveFileBySlug(ctx context.Context, p file.RetrieveFileBySlugParam) (*file.RetrieveFileBySlugResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveFileBySlug", ctx, p)
	ret0, _ := ret[0].(*file.RetrieveFileBySlugResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// RetrieveFileBySlug indicates an expected call of RetrieveFileBySlug.
func (mr *MockFileMockRecorder) RetrieveFileBySlug(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveFileBySlug", reflect.TypeOf((*MockFile)(nil).RetrieveFileBySlug), ctx, p)
}

// ScheduleReplication mocks base method.
func (m *MockFile) ScheduleReplication(ctx context.Context, p file.ScheduleReplicationParam) (*file.ScheduleReplicationResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleReplication", ctx, p)
	ret0, _ := ret[0].(*file.ScheduleReplicationResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// ScheduleReplication indicates an expected call of ScheduleReplication.
func (mr *MockFileMockRecorder) ScheduleReplication(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleReplication", reflect.TypeOf((*MockFile)(nil).ScheduleReplication), ctx, p)
}

// SearchFile mocks base method.
func (m *MockFile) SearchFile(ctx context.Context, p file.SearchFileParam) (*file.SearchFileResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFile", ctx, p)
	ret0, _ := ret[0].(*file.SearchFileResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// SearchFile indicates an expected call of SearchFile.
func (mr *MockFileMockRecorder) SearchFile(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFile", reflect.TypeOf((*MockFile)(nil).SearchFile), ctx, p)
}

// UploadFile mocks base method.
func (m *MockFile) UploadFile(ctx context.Context, p file.UploadFileParam) (*file.UploadFileResult, *system.SystemError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, p)
	ret0, _ := ret[0].(*file.UploadFileResult)
	ret1, _ := ret[1].(*system.SystemError)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileMockRecorder) UploadFile(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFile)(nil).UploadFile), ctx, p)
}
