APP_NAME = "chariot"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 20110

REPOSITORY_PROVIDER = "mysql"

MYSQL_PRIMARY_HOST = "localhost"
MYSQL_PRIMARY_PORT = 3400
MYSQL_PRIMARY_USER = "admin"
MYSQL_PRIMARY_PASSWORD = "123456"
MYSQL_PRIMARY_DB_NAME = "chariot"

MYSQL_SECONDARY_HOST = "localhost"
MYSQL_SECONDARY_PORT = 3401
MYSQL_SECONDARY_USER = "admin"
MYSQL_SECONDARY_PASSWORD = "123456"
MYSQL_SECONDARY_DB_NAME = "chariot"

STORAGE_ACCESS_HOST = "http://localhost:20110"
STORAGE_FORM_SIZE = 1073741824

QUEUE_PROVIDER = "rabbitmq"
QUEUE_RABBITMQ_PROTO = "amqp"
QUEUE_RABBITMQ_HOST = "localhost"
QUEUE_RABBITMQ_PORT = 5672
QUEUE_RABBITMQ_USER = "guest"
QUEUE_RABBITMQ_PASSWORD = "guest"

SIGNATURE_ISSUER = "chariot"
SIGNATURE_KEY = "-----BEGIN RSA PRIVATE KEY-----MIIEoQIBAAKCAQBjXu56Nt/27NGrPkCOgowt9+t1I7N23YrjiM6AECshvY/yZQRHJKPPY6KMlWDRjzk2wr9S2T6GDxLV7ZWt3F8/nr1f3QuOVM/QGBdM4tNXAhO/cKpwedR8IZOon394Eku/X+98B28RUp+DKXzthqJePzCrEfiVc3ZJC4TH9n5zxDeOsE8CHr/9+PCKvOn1pp2IVqF/dipecOV7snrMF1WgyrHtuMf7mFcOIlZ2wD+9XE1sJ9qm3GgYcklqXh76SlsyMVKRHDq/Y77rr1VQeXCyggVVDtrXalnXAiWpQwp/MpDytLl6ojtl44EOldfQCPVNKvhqRRJoaJiSzZ9GBxy9AgMBAAECggEAMg5fCPddiHAxChb4xBDk9j79v+s0+vqMfSOsCfybDYsE2PCj4AaH8e9ZsYGJ3OZNxtUBNYWzpiovrc3ZaVQqMs0Ozhx2NsNoT4XjLtrP5PNp6TSi1re4HrN3QyjdOCnXOFbmN08zVsGNErAyeyAn6FviczpBQ19/RTplL6lud3fNPAF/WYRIFFmn03JOkCWUnmcDe5NAbnFhQAgtIErf6w9AI4Bzh4OirefHSYRBF5lS0yiGwviZWcgcbY8Lo4es/ieXv1JLP1CDmrPgd+hTccxirVu/EFlGiwMys6Vtr0817rU/EtBw0z4/4ZhyOKziBb+u9sUdpJ/w8ANeDqeLQQKBgQCz+VdUT1M+lm7u80L6Je3kGVu/yRkZ9c+PQ4oNFZclL0UCn3wU9+t4ktZmqQXqsB+q45tbY23sKknJC8zv/dUc+6RvGmJwSf7GvskWq+EYOIZGN9cSKoLNELZxmstBdCsTrj3FkQi5N/n+BGoSwdlQ9XtbMwxcYgbfWcbmft/gTQKBgQCNWQrxWqb0LJlZ3k4ZsqQZYV2s2GB91crFhkoHFf9miCAVYVrtGJKKfPvK0e02chy4xQYKx2UtGkchUyYXkiAkDvODOxfZScrnOuZ71+KVrJk0xoTiQb/4vw4UlAfglICRCMrP1ob8WrGluBozDWbvHU3yuqMDuixsHrKB1EjmMQKBgGYhvnw60+u1pNh3NfAM7DZAab+pWFRSGWqcklAgi3hvncMCTID9vCPdeEwj6Raowh/RME2pXCzkRqEP0En1CyZ6a3MdTvWYGDwi8qyp94AuO4zHjYZil33V2SMZC/Vl/jgZ7jYauw+ZA4YybRud5Dw8QrebfY1Dl9DR+ry9DUEVAoGAOaRESCS1zQGbEAEOTICDVy5TqzcaMnbLGD4pVjZsTv3YR5/KGsJYkE1jyVROrlNezyLZ0e96nSgINdjYwef/X3URbUTd9uiW7DEi6QIjDvKyD8mdSz+Q7/nJ3i53/+fPflXdj2Bm7+Z0Z6ZqWMNwZLbIoOHntI9pqjXiiftuNyECgYAM/YCkcipp+MOb01krYg7YM8EIotH5pc6AdjiT5BlE+FnwLWBM/+N0jf/fuGP8M0MNVSx7axb2EZCVy58OxkhS5tVuMePi3wYh1Z9xW+thoZRE76SBzYrEOZzUil4LVFKPvGSMfsNzoQpQ44m4eU2HIigcZSL5fBkq8AdbXOq99w==-----END RSA PRIVATE KEY-----"

[BARRELS]
