APP_NAME = "chariot"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 3030

REPOSITORY_PROVIDER = "mysql"

MYSQL_PRIMARY_HOST = "localhost"
MYSQL_PRIMARY_PORT = 3400
MYSQL_PRIMARY_USER = "admin"
MYSQL_PRIMARY_PASSWORD = "123456"
MYSQL_PRIMARY_DB_NAME = "chariot"

MYSQL_SECONDARY_HOST = "localhost"
MYSQL_SECONDARY_PORT = 3401
MYSQL_SECONDARY_USER = "admin"
MYSQL_SECONDARY_PASSWORD = "123456"
MYSQL_SECONDARY_DB_NAME = "chariot"

UPLOAD_FORM_SIZE = 1073741824

[BARRELS]

[BARRELS.HIPPO1]
PROVIDER = "goseidon_hippo"
HIPPO_SERVER_HOST = "http://localhost:3000"
HIPPO_CLIENT_ID = "chariot"
HIPPO_CLIENT_SECRET = "storage!@#$%"
