APP_NAME = "chariot"
APP_ENV = "local"
APP_VERSION = "1.0.0"
APP_DEBUG = true

REST_APP_HOST = "localhost"
REST_APP_PORT = 3030

REPOSITORY_PROVIDER = "mysql"

MYSQL_PRIMARY_HOST = "localhost"
MYSQL_PRIMARY_PORT = 3300
MYSQL_PRIMARY_USER = "admin"
MYSQL_PRIMARY_PASSWORD = "123456"
MYSQL_PRIMARY_DB_NAME = "chariot"

MYSQL_SECONDARY_HOST = "localhost"
MYSQL_SECONDARY_PORT = 3301
MYSQL_SECONDARY_USER = "admin"
MYSQL_SECONDARY_PASSWORD = "123456"
MYSQL_SECONDARY_DB_NAME = "chariot"

UPLOAD_FORM_SIZE = 1073741824
